# Generated by Django 6.0.3 on 2026-03-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_full_name_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Landlords require admin approval before they can login'),
        ),
    ]
