# Generated by Django 6.0.3 on 2026-03-31 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_approved'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaretakerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caretaker', models.ForeignKey(limit_choices_to={'role': 'caretaker'}, on_delete=django.db.models.deletion.CASCADE, related_name='caretaker_assignments', to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(limit_choices_to={'role': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_caretakers', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caretaker_assignments', to='properties.property')),
            ],
            options={
                'db_table': 'caretaker_assignments',
                'unique_together': {('caretaker', 'property')},
            },
        ),
    ]
