# Generated by Django 6.0.3 on 2026-04-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordsettings',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Name on the bank account (as it appears on the statement)', max_length=100),
        ),
        migrations.AddField(
            model_name='landlordsettings',
            name='card_enabled',
            field=models.BooleanField(default=True, help_text='Allow tenants to pay via card (Paystack)'),
        ),
        migrations.AddField(
            model_name='landlordsettings',
            name='mpesa_type',
            field=models.CharField(choices=[('stk_push', 'STK Push (system sends prompt)'), ('paybill', 'Paybill'), ('till', 'Till Number')], default='stk_push', help_text='How tenants should pay via M-Pesa', max_length=10),
        ),
        migrations.AlterField(
            model_name='landlordsettings',
            name='mpesa_account',
            field=models.CharField(blank=True, help_text='Account reference tenants type when using paybill', max_length=50),
        ),
    ]
