# Generated by Django 6.0.3 on 2026-04-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_landlord_settings_mpesa_type_card_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordsettings',
            name='mpesa_type',
            field=models.CharField(choices=[('paybill', 'Paybill'), ('till', 'Till Number')], default='paybill', help_text='M-Pesa destination: paybill or till number', max_length=10),
        ),
    ]
