# Generated by Django 6.0.3 on 2026-03-24 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lease_start_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('ended', 'Ended')], default='pending', max_length=10)),
                ('rent_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(limit_choices_to={'role': 'landlord'}, on_delete=django.db.models.deletion.PROTECT, related_name='managed_tenancies', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(limit_choices_to={'role': 'tenant'}, on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='properties.unit')),
            ],
            options={
                'db_table': 'tenancies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenancyAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(max_length=150)),
                ('tenant_phone', models.CharField(max_length=15)),
                ('tenant_id_number', models.CharField(max_length=20)),
                ('landlord_name', models.CharField(max_length=150)),
                ('landlord_phone', models.CharField(max_length=15)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('property_name', models.CharField(max_length=200)),
                ('unit_number', models.CharField(max_length=20)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lease_start_date', models.DateField()),
                ('signed_name', models.CharField(max_length=150)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('agreement_pdf', models.FileField(blank=True, null=True, upload_to='agreements/')),
                ('tenancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='tenancies.tenancy')),
            ],
            options={
                'db_table': 'tenancy_agreements',
            },
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active'])), fields=('unit',), name='unique_active_tenancy_per_unit'),
        ),
    ]
