# Generated by Django 6.0.3 on 2026-04-08 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='tenant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'tenant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenancies', to=settings.AUTH_USER_MODEL),
        ),
    ]
