# Generated by Django 6.0.3 on 2026-04-10 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPayoutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_type', models.CharField(choices=[('paybill', 'Paybill'), ('till', 'Till Number')], default='paybill', max_length=10)),
                ('paybill_number', models.CharField(blank=True, max_length=20)),
                ('till_number', models.CharField(blank=True, max_length=20)),
                ('mpesa_account', models.CharField(blank=True, help_text='Account reference tenants type when using paybill', max_length=50)),
                ('card_enabled', models.BooleanField(default=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_settings', to='properties.property')),
            ],
            options={
                'db_table': 'property_payout_settings',
            },
        ),
    ]
