# Generated by Django 6.0.3 on 2026-03-30 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('tenancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('initial', 'Initial Payment'), ('monthly', 'Monthly Rent'), ('1_day', '1 Day'), ('1_week', '1 Week'), ('3_months', '3 Months'), ('6_months', '6 Months')], max_length=10),
        ),
        migrations.CreateModel(
            name='UnitPaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('paid_ahead', 'Paid Ahead')], default='unpaid', max_length=15)),
                ('amount_paid_this_period', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('paid_until', models.DateField(blank=True, null=True)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_status', to='tenancies.tenancy')),
            ],
            options={
                'db_table': 'unit_payment_status',
            },
        ),
    ]
