# Generated by Django 6.0.3 on 2026-04-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_payment_type_unitpaymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('initial', 'Initial Payment'), ('monthly', 'Monthly Rent'), ('1_day', '1 Day'), ('1_week', '1 Week'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('balance', 'Pay Balance')], max_length=10),
        ),
    ]
